#!/bin/bash
#$ -cwd             # Set the working directory for the job to the current directory
#$ -pe smp 1	      # Request 1 cores
#$ -l h_rt=240:0:0  # Request 240 hour runtime
#$ -l h_vmem=16G   # Request 16GB RAM
#$ -j y              # Combine the standard output and standard error stream
#$ -N CHROM_3L       # Give a specific name to the job
#$ -o log_file/      # output log of each job



# Command section
module load plink/1.9-170906


# Stop script if error occurs
set -e


mkdir -p /data/home/bty155/ondemand/data/Phase2/Linkage_Pruning/2024-01-25-Linkage_Pruning_Pass

VCF=/data/SBBS-FumagalliLab/mosquito_gan/phase2/production/phase2/AR1/variation/main/vcf/pass/ag1000g.phase2.ar1.pass.3L.vcf.gz

OUT=/data/home/bty155/ondemand/data/Phase_2/Linkage_Pruning/2024-01-25-Linkage_Pruning_Pass/Linkage_pruning_pass


#PERFORM LINKAGE PRUNING
plink --vcf $VCF --double-id --allow-extra-chr \
--set-missing-var-ids @:# \
--indep-pairwise 50 10 0.1 --out $OUT
