#!/bin/bash
#$ -cwd           # Set the working directory for the job to the current directory
#$ -pe smp 1	  # Request 1 cores
#$ -l h_rt=240:0:0  # Request 240 hour runtime
#$ -l h_vmem=16G   # Request 16GB RAM
#$ -j y              # Combine the standard output and standard error stream
#S -N CHROM_3L       # Give a specific name to the job
#$ -o log_file/      # output log of each job



# Command section
module load plink/1.9-170906


# Stop script if error occurs
set -e

mkdir -p /data/SBBS-FumagalliLab/mosquito_gan/DistanceMatrix_Ph2/2024-02-26-Sample

VCF=/data/home/bty155/ondemand/data/Phase_2/MY1.vcf.gz

OUT=/data/SBBS-FumagalliLab/mosquito_gan/DistanceMatrix_Ph2/2024-02-26-Sample/dist_matrix

#CALCULATE DISTANCE MATRIX
plink --vcf $VCF --distance 1-ibs flat-missing square --double-id --allow-extra-chr --out $OUT

