#!/bin/bash
#$ -cwd           # Set the working directory for the job to the current directory
#$ -pe smp 2	  # Request 1 cores
#$ -l h_rt=1:0:0  # Request 240 hour runtime
#$ -l h_vmem=32G   # Request 64GB RAM
#$ -j y              # Combine the standard output and standard error stream
#S -N CHROM_3L       # Give a specific name to the job
#$ -o log_file/      # output log of each job



# Command section
#module load gcc/8.2.0
#module load vcftools/0.1.16
module load bcftools/1.16

# Stop script if error occurs
set -e

mkdir -p /data3/scratch/bty155/Phase2/Chrom_3R/Split_vcf_3R_files/2024Dec23a_Results_Vcf_3R_files

VCF=/data/SBBS-FumagalliLab/mosquito_gan/phase2_3R/ag1000g.phase2.ar1.pass.3R.vcf.gz

SAMPL=/data/home/bty155/ondemand/data/Phase_2/Mayotte.txt

OUT=/data3/scratch/bty155/Phase2/Chrom_3R/Split_vcf_3R_files/2024Dec23a_Results_Vcf_3R_files/Mayotte.vcf.gz


#CODE

bcftools view -S $SAMPL --force-samples $VCF >  $OUT

mkdir -p /data3/scratch/bty155/Phase2/Chrom_3R/Split_vcf_3R_files/2024Dec23_Results_Vcf_3R_files

